version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: oes-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: OES_Project
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    command: ["mysqld", "--default-authentication-plugin=mysql_native_password"]
  app:
    build: .
    container_name: oes-app
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: OES_Project
      DB_USER: root
      DB_PASS: root
    ports:
      - "8080:8080"
    restart: unless-stopped
volumes:
  db_data:
