name: CI Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Temurin JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '11'
          cache: maven
      - name: Build WAR
        run: mvn -q -f OES/pom.xml package -DskipTests
      - name: Archive WAR
        uses: actions/upload-artifact@v4
        with:
          name: OES-war
          path: OES/target/OES.war
      - name: Build Docker image
        run: docker build -t oes-app:ci .
